language: java
jdk: oraclejdk8
script:
  - gradle fatjar
deploy:
    provider: releases
    api_key: $GITHUB_OAUTH
    file_glob: true
    file: "build/libs/donorschoose-*.jar"
    zip_file: 'build/libs/donorschoose-*.jar'
    skip_cleanup: true
    on:
      tags: true